redis-ha:
  enabled: true

controller:
  replicas: 3

server:
  replicas: 3

repoServer:
  replicas: 3

applicationSet:
  replicas: 3

configs:
  secret:
    # FIXME: Change
    argocdServerAdminPassword: "$2b$14$thNCIvoVrECe8Ch9buVve.m6M53hLXlugkbIwN8yrVPp2m2Cobkey"

global:
  domain: argocd.dhm-ctf.de

  affinity:
    podAntiAffinity: hard

notifications:
  notifiers:
    service.github: "ref+sops://kubernetes/secrets/github.sops.yaml#argoServiceConfig"
  secret:
    items:
      githubPrivateKey: "ref+sops://kubernetes/secrets/github.sops.yaml#appPrivateKey"

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: sops-private-key
    type: Opaque
    stringData:
      privateKey: "ref+sops://kubernetes/secrets/argocd.sops.yaml#ageSecret"
  - apiVersion: v1
    kind: Secret
    metadata:
      name: infra-repo
      labels:
        argocd.argoproj.io/secret-type: repository
    type: Opaque
    stringData:
      url: "https://github.com/nfits/dhm-infra.git"
      name: "infra-repo"
      githubAppID: "ref+sops://kubernetes/secrets/github.sops.yaml#appID"
      githubAppInstallationID: "ref+sops://kubernetes/secrets/github.sops.yaml#appInstallationID"
      githubAppPrivateKey: "ref+sops://kubernetes/secrets/github.sops.yaml#appPrivateKey"
