apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway
spec:
  secretName: main-tls
  commonName: dhm-ctf.de
  dnsNames:
    - dhm-ctf.de
    - "*.dhm-ctf.de"
    - "*.svc.dhm-ctf.de"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    # FIXME: Use non-staging letsencrypt
    name: letsencrypt-staging
