apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: services
spec:
  blocks:
    - start: "193.56.133.168"
      stop: "193.56.133.175"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: services
spec:
  nodeSelector:
    matchExpressions:
      - key: node.kubernetes.io/exclude-from-external-load-balancers
        operator: DoesNotExist
  interfaces:
    - cluster
  loadBalancerIPs: true
