ageSecret: ENC[AES256_GCM,data:58oz8HdKPyrVbvcjVb/BqbZ5rTB76ELtqtIcjoo15IehWrcmW2p8Slhr5S11zHMzA/5U+rnzKMuFOIiw+QBME/Ru6PFoK8k+M0w=,iv:spNraz4lkdX8jeOSYVdHZoxlJlDtC4j5f44eCdUwJ1Y=,tag:N185dxXuLaUK8B5hPbUIwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgqz87qgxh8qg8urrccz3tlr3htugwpk4sucmfys2k3c9srwv9aquzlguj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYnFoUmRGM3EvQzI3ck1a
            TUpjREdDNE42R05veXpZMkp5S2laYVNmbFZvCkJNRkZVQUtldW5BeWx0Z0h3TWl1
            Uzk1TS83UGEwbjJ4WWpxTHc1bmFIbEkKLS0tIHNPOWNybmVROW9GaUVBd0JzRWZy
            eVBpLzRTb1dkbVlCUVJHdGU5c2xVL00Kcz+vFmQti/hWjnsd1iARXQdfD2M3Y841
            4S6Toi/Z2FnrxUCE8Wh2w9NNuiH04d5pBt5XL5q/0eYz4WQYKEL07A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T06:14:58Z"
    mac: ENC[AES256_GCM,data:2BB28XQBIkqA0XpZddWRQvtc8NvBywMppTuf1yh0a9iCEq/eGWVzqdhWT74sMxvcUhFLA5LFydzlWTEI0OIYNsADYauwA/agtBLO8k5IaR83waUg970AqFyj8Ds1NR41pGpaJqDkDOWuEKvirs00RE1l4ht94O+KiDaouOIPkFc=,iv:6G0lf04Buhs0hgr2WjGEiUGJHDJQZh01jf5WSG9SLKA=,tag:3FJSh/CeYnYba0RQwtv0ag==,type:str]
    pgp:
        - created_at: "2024-06-21T06:14:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Df7voni2Kxl4SAQdA9jAerebQoEdlVgTnrNFR9lVmGYEJdMVEp/fpbGlStwIw
            RpX5UzZPZMyMHw//tn6vUCe3Hy29kjqLAwpht/hrRoFB3Tw6wn0jP1LZod5A+/ec
            0l4BTsf1a5t3mj+qzeVc6iizxD5Si6o2Hg/fzPkQFYYONZB3ivc4CGIseeBG25tJ
            +Fc+rSGGWLtzXSx13DtpWWd8vxAqCI1hMNGlJgVphvJqsMWbuBWkfkZjMYxu9sta
            =fnZP
            -----END PGP MESSAGE-----
          fp: CE12ED73C6D5DE0516516DCC397761D5D102CB9D
        - created_at: "2024-06-21T06:14:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA7b93FlXgFUkAQf9EuPEJBrPEp75etdtdbcJ6NnFusKm3vNOSUVNw1Q8C7UD
            TyfwRuOW87Pdkj1s4NhSsnwyk4XdcqRF2Ve0k8K3i9hDpVZ4iY6qD4uDGNE/bL4F
            B4TLHsqNKb3EX+Y91ItobqeI7Ij6isIxDoIG1UVFD6diImzcbdBG3vTOWHGn/Fjq
            Y0+0ssQ07uNUDbx2rx6hGpwfmyHMT4OYmq/1M5ku3KLfYP8gO2Ox57UYd/JpFZmU
            LC32ESy4b2JcHKM1+77arEaly0FgDSAhLwrwWdK8MwA1reRBuTwaHqRB7kTXV8a/
            e+HkyXyfh75793zPx0xzC0AUUiyRFYbUUAX+GhEl9tJeAav45GHWN3cNU73+M7el
            2yxk2DGGcCWEuZ5/t2bAUP4rL4xbzymBbKGA33hicLUQWQaXgtbKC1xswVrKhkTD
            c/3vijBG9PykzQSVImUAWQNqAazm1FLVf9TSp7B9MQ==
            =5H51
            -----END PGP MESSAGE-----
          fp: 3C2F2605E078A1E18F4793909C4DBE6CF438F333
    unencrypted_suffix: _unencrypted
    version: 3.8.1
