ageSecret: ENC[AES256_GCM,data:58oz8HdKPyrVbvcjVb/BqbZ5rTB76ELtqtIcjoo15IehWrcmW2p8Slhr5S11zHMzA/5U+rnzKMuFOIiw+QBME/Ru6PFoK8k+M0w=,iv:spNraz4lkdX8jeOSYVdHZoxlJlDtC4j5f44eCdUwJ1Y=,tag:N185dxXuLaUK8B5hPbUIwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgqz87qgxh8qg8urrccz3tlr3htugwpk4sucmfys2k3c9srwv9aquzlguj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RnpvR0ZGME5YLy9EdDlV
            OVhrL1U2ZE54YzNITXAxQkxNQXNCVUxxNngwCnNyYXdIUVJkSXk3OWxjak4vUU9z
            WmRqN0JLT0w3QjE3UmNRRDNlaGcwNXMKLS0tIDZva3hHKzhwMXljZmlKeXg4dFl0
            Z1B0NFdPTjIrUlNZYTBWaW9VeGpyM2cKQ4WCo1hi3WzVxjqluSgtLitCKCo4Q1H+
            who3PPqAy/6pfWijmn9e4e1UkfB3b6LcLOozjegGMFzXIPOIR/40MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T06:14:58Z"
    mac: ENC[AES256_GCM,data:2BB28XQBIkqA0XpZddWRQvtc8NvBywMppTuf1yh0a9iCEq/eGWVzqdhWT74sMxvcUhFLA5LFydzlWTEI0OIYNsADYauwA/agtBLO8k5IaR83waUg970AqFyj8Ds1NR41pGpaJqDkDOWuEKvirs00RE1l4ht94O+KiDaouOIPkFc=,iv:6G0lf04Buhs0hgr2WjGEiUGJHDJQZh01jf5WSG9SLKA=,tag:3FJSh/CeYnYba0RQwtv0ag==,type:str]
    pgp:
        - created_at: "2024-06-24T09:58:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Df7voni2Kxl4SAQdAmeO9k8Qdz9DjIBZvA150yKhdEJfAE1imSlbQ5yklACcw
            41Fjsub/Ty31fVfQS9eHte2i5f3AMNe2mAFjnq0Ax6CKnn31QeCldywUU11VNiJ5
            0l4BhOOn8C3RPeVrXZDqyNho0+AOalcK1Qd6wyEMVG3AB7EVXWeX2CAt/JPUUffm
            zxxVmM6gqwfyMjMELOOt02AR/Vq2GOa1rNW3oRVbEd664dbs6+OH1SOLdpnuq0jb
            =w3a3
            -----END PGP MESSAGE-----
          fp: CE12ED73C6D5DE0516516DCC397761D5D102CB9D
        - created_at: "2024-06-24T09:58:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA7b93FlXgFUkAQgAx6+VKZ8g+wS4W+6giIOih8yu4baiLq4oSBL4vEqulVo2
            St0/Ks5W2cKJNWlclvICS10sgesCkNJPVyXbwVVCscePtOZeRQbtPVpbLwOe947r
            jqAJn6cumwtbSY3ysDXEqvbN4AUiLDXlRWyIScD2yh/2V/UjNTGN2tUwCGamzdfj
            KZSn1LcPKZV0+n2RqYJp6hJf0QQWD3uDzC65Oc8m2QYQ7hn97IExPFPMpSQgJC5O
            atL/bdoNqMc8z9OMuQstm59IrbbsuZ0qOrpgxgvva0TrfVUaz/vxF9eTOtrPRfGd
            cK/VtYQw6sFAwMpBV9kEQXvOL2pDVkf+kLbfjN7ectJeAZ9CTE2lqztrVaJtWmLW
            ZZRJ25EtgMMbCeP3uaz3XoDv29z41RwLHgzMbmHb5WBM92L0W1Zu9NuDFWbkfK2W
            9IWQP6JV+++kTua8yvvxRQvm3/To08pfIq2q4FtiIw==
            =TO2Z
            -----END PGP MESSAGE-----
          fp: 3C2F2605E078A1E18F4793909C4DBE6CF438F333
        - created_at: "2024-06-24T09:58:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtNl1HXvePigSAQdArXVzwklWf8BFHPZ+tvsY5W5esx2SKj16lYqtGqmdRH0w
            dMB6/nJ6xZ2nxpmw1EFSzK+1Y+nPvJ7nSJtSmBq7DtvnMqg6GnYgqYXX9OluqPW8
            1GgBCQIQ3HWMt3H00WkyjEAYfe/tN8ytBCRulYe3iPRIuui4iFMOp6EWI+qa+EOz
            tDwaSEt7eXt2nfNMaXzhRBdJmKuTo52u0uevP36UJgP1oXpUkNGoYMx1zAqZSTBB
            UvWiyQNIDs0yww==
            =Mb/4
            -----END PGP MESSAGE-----
          fp: DD939AD813A3EACB116A7F4B28244753C35D3D10
    unencrypted_suffix: _unencrypted
    version: 3.8.1
