auth:
  discord:
    enabled: true

    admins:
      - "684313101465550879" # Patrick (NFITS)
      - "148458355860570112" # Daniel (NFITS)
      - "474659539803701259" # Alain (NFITS)
      - "534109324193300503" # Felipe (NFITS)
      - "469574966279667712" # Thomas (NFITS)
      - "731828453367742506" # Kolja (NFITS)
      - "166211731503316993" # Tobias (FluxFingers, External Authors)
      - "488765441032847394" # Felix (FluxFingers, External Authors)
      - "367674689449099264" # Gina (RedRocket)
      - "316999264792346635" # Tobias (NFITS)
      - "305018323907641344" # Jan-Niklas (RedRocket)
      - "226729542734053377" # Lukas (lukas2511) (RedRocket)
      - "217696462371422208" # Lukas (RedRocket)
      - "222796095745556480" # Apfelsaft (Betatester (Tobi (NFITS)))
      - "729418872045961359" # Ruben (RedRocket)
      - "653830824697004063" # Fabian (Betatester (Tobi (NFITS)))
      - "653368699000193095" # Smartsmurf (Betatester (Tobi (NFITS)))

api:
  replicaCount: 3
  image:
    repository: harbor.dhm-ctf.de/ghcr/nfits/ctf-platform/platform

  config:
    url: "https://api.dhm-ctf.de"

  grpcRoute:
    enabled: false
    hostnames:
      - api.dhm-ctf.de

    parentRefs:
      - name: main
        namespace: gateway-system
        sectionName: https

broker:
  replicaCount: 3
  image:
    repository: harbor.dhm-ctf.de/ghcr/nfits/ctf-platform/platform

  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "challenges.dhm-ctf.de,*.challenges.dhm-ctf.de"

  config:
    tls:
      secretName: broker-tls

frontend:
  image:
    repository: harbor.dhm-ctf.de/ghcr/nfits/ctf-platform/web
    tag: cscg

  config:
    url: "https://play.dhm-ctf.de"

  httpRoute:
    enabled: true
    hostnames:
      - play.dhm-ctf.de

    parentRefs:
      - name: main
        namespace: gateway-system
        sectionName: https

staticFiles:
  replicaCount: 3
  podAntiAffinityPreset: hard

  config:
    url: "https://static.dhm-ctf.de"

  httpRoute:
    enabled: true
    hostnames:
      - static.dhm-ctf.de

    parentRefs:
      - name: main
        namespace: gateway-system
        sectionName: https

  storage:
    size: 10Gi

etcd:
  replicaCount: 3
  podAntiAffinityPreset: hard

  persistence:
    enabled: true
    size: 8Gi
    storageClass: longhorn-local-only

  networkPolicy:
    ingressNSMatchLabels:
      platform-etcd-access: "true"

imagePullSecrets:
  - name: registry-credentials

challenges:
  domain: challenges.dhm-ctf.de
  namespace: challenges
  registry: harbor.dhm-ctf.de/internal/challenges
  registryCredentialName: registry-credentials

  networkPolicies:
    required:
      - default
    available:
      - default
      - allow-outgoing

extraDeploy:
  - apiVersion: cilium.io/v2
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: broker-policy-default
    spec:
      endpointSelector:
        matchLabels:
          broker-policy/default: "true"
      egress:
        - toPorts:
            - ports:
                - port: "53"
                  protocol: ANY
          toEndpoints:
            - matchLabels:
                k8s:io.kubernetes.pod.namespace: kube-system
                k8s:k8s-app: kube-dns
  - apiVersion: cilium.io/v2
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: broker-policy-allow-outgoing
    spec:
      endpointSelector:
        matchLabels:
          broker-policy/allow-outgoing: "true"
      egress:
        - toEntities:
            - world
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: broker-tls
    spec:
      secretName: broker-tls
      commonName: challenges.dhm-ctf.de
      dnsNames:
        - challenges.dhm-ctf.de
        - "*.challenges.dhm-ctf.de"
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: letsencrypt
  # TODO: Debug why nginx doesn't work
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ctf-platform-api-proxy
      namespace: gateway-system
    data:
      Caddyfile: |
        api.dhm-ctf.de {
          tls /cert/tls.crt /cert/tls.key
          reverse_proxy ctf-platform-api.ctf-platform.svc:80
        }
  - apiVersion: v1
    kind: Service
    metadata:
      name: ctf-platform-api-proxy
      namespace: gateway-system
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "api.dhm-ctf.de"
    spec:
      type: LoadBalancer
      selector:
        app.kubernetes.io/name: ctf-platform-api-proxy
      ports:
        - port: 443
          targetPort: https
          protocol: TCP
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: ctf-platform-api-proxy
      namespace: gateway-system
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: ctf-platform-api-proxy
      template:
        metadata:
          name: api
          labels:
            app.kubernetes.io/name: ctf-platform-api-proxy
        spec:
          containers:
            - name: caddy
              image: caddy
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /etc/caddy/Caddyfile
                  name: config
                  subPath: "Caddyfile"
                  readOnly: true
                - mountPath: /cert
                  name: tls
                  readOnly: true
              ports:
                - containerPort: 443
                  name: https
          volumes:
            - name: config
              configMap:
                name: ctf-platform-api-proxy
            - name: tls
              secret:
                secretName: main-tls
          restartPolicy: Always
