cloudflare:
    apiToken: ENC[AES256_GCM,data:kdX2Se/EjJ4Ofyywx2Qog77VoaMd4zkY0LerIlgW3j24RdQi20aXQw==,iv:RoXxHA2UcScW1lWjmqDJiHqNhAfC1UIIz239aHiZdJo=,tag:T9VrAgDy5LADMOapcvbNJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgqz87qgxh8qg8urrccz3tlr3htugwpk4sucmfys2k3c9srwv9aquzlguj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQTgyUXo3VlExOGV3WERY
            eHdCQ3RlMlBLUnEyeDZOcm9ZQVc3V2ZhbGh3CmljZTRkY3Fkc3FZTlVQaDV3cVAy
            WDFYOWJZcWs5OGEvVUVwajBDejc1ZGcKLS0tIGFxNG5uVWpGdFM0T2ZQdndqdmkr
            ME9LTnZDSzJ6WjRxNVJwaUtZakc2WjgKn+x8wZTz3leVUbbSgX2QQAbjXfavNbk6
            4eXUUzGMwaMXNRgYNLiQ1TGUWyjq4UPN9fhoOYq6UvVM4bmIIvtx9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T07:40:02Z"
    mac: ENC[AES256_GCM,data:aE4zhaiOkMMvC6gcpnmei3jx0T2Y0WSF3yQsN7Ea1YJBiLKtJ5ZsvvX/t/2I2ulFMi36/mWz49vOwioNqK9mkfQ2zTV4xvprbXV09LDk/KTBWi+48VjgeFk2Hldi/y+c0FE93ZWaEHiLeaxz5ydN3FYfFLCVvEWMBUzrbXJVDVc=,iv:hXTJ2gd8A5C+5N2b8Pt6MUj6lHD/JLFWvZ8JVnx4MkE=,tag:1e5cwDz8alWDBHTLKwcYbA==,type:str]
    pgp:
        - created_at: "2024-06-24T17:49:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Df7voni2Kxl4SAQdAEFtyY6dQnhce7l4HWg/gKeL4+YhYVoJ4rZ9IKPUMq2Aw
            /SGb1cwijQEshkXNrlgk7F447MMbWacaUaQv82yQ5jtRS3GRGZvDQ6zhkYOJjNew
            0l4BNeJU/Hc3vpAYN/RHGeLwJyVLnenjtewPwq4PX5YnOZmn8SnG7DBUh8lyuXyv
            Qy4xaF+a7+ApMnNEqaBiIf7pzFelNu97lNI5I2cAI7OOuobaoPiNuXcdFB8/Ce+3
            =1dFd
            -----END PGP MESSAGE-----
          fp: CE12ED73C6D5DE0516516DCC397761D5D102CB9D
        - created_at: "2024-06-24T17:49:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA7b93FlXgFUkAQf+NS88Hp7dRU3oiTkGGAOJdysZJo0q4YOWRGifqAu8RD4Y
            8UGpDbTOQrNrdZXadZ/4pqJ/vtGQkZO1NphXfOaXtT2ZICmVpzc7UL6pOU4ELB/g
            i3NReCHK+h4ixtGDGCkddpXIRpSa9Cj92ZYUxkgCWXxRgwimJ42MhsnSv05cdL9v
            xUXPbS5FNvmwbz4zLPOLcYMeFOIb+klWxXv+OAE1KVIYHPUJbqjLtoAQ5WfiXz+/
            etA30UDrDGkfDlEOU2dbqTYXs7GyhTt673K1kMC/BQg4k4JjJBUI1cxAQg1wRSX2
            snleLqMfSubSSD4LXRE4Kq8fkdw5Ve/K7P5njzOiMdJeAQ54BTKsY6ZTF5fT3lNz
            C4fFcSOJHFUX5WSiQjJIQWdYXsbnbvW0DqRi4KiSn0gLVej2bX9g32+o0elydu/t
            MYxcu6jz+xqxTUzg0s93LJnSjwhkJQ3LJaBLuvbjJg==
            =BrgF
            -----END PGP MESSAGE-----
          fp: 3C2F2605E078A1E18F4793909C4DBE6CF438F333
        - created_at: "2024-06-24T17:49:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtNl1HXvePigSAQdAEREekvGOD4cQTAKCo0Dvaw1vowRE3GldZENnaRRRNigw
            muAWpIBEmsQntMp6zorUdGnS0dspD2NrIm0pYt36+8ep+oUJycjiIsKxAVNsneCI
            1GgBCQIQCuLzBWQe0G/LQG4C6W9Tc/1Z4uyWPargctQDASmtYt/aS2MRRcggdCLb
            tIpWo9t8P42e+DD210CJVZVLMW1cArfmZPyVu2BguZWdyl/Cf+b8nT579Vu1QWOw
            PPjIlLJfPdJncw==
            =tFzk
            -----END PGP MESSAGE-----
          fp: DD939AD813A3EACB116A7F4B28244753C35D3D10
        - created_at: "2024-06-24T17:49:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D66o4m5qj3wgSAQdAiBbuCbq7DOEUDIREE0PBFwL4/9zzmLHYOuEcgYnOOTQw
            lTLKeR9khUu0ac35O96V6oExfUa0bTEIcUBZCMH3OeAEdn7dGgzUhjHJRL7knkHo
            1GgBCQIQkZGmgp+bvjSYjdVSYYKCqo+2keamZSVUg+D9hUQ7QkTJROosmzhts7SQ
            l4XMQ0sYk99OgXCcGcdaaxgYHeU8/+KaAUK5SbdnIgi6qJPO8nSkp9lDEkO8dhIY
            1h5mM1BrCJiVcw==
            =HZPG
            -----END PGP MESSAGE-----
          fp: FB519CBC730981016A5478A160A17D46CFFB2A45
    unencrypted_suffix: _unencrypted
    version: 3.8.1
