extraObjects:
    - ENC[AES256_GCM,data:+sYLWZRY4gNlmst+p/eIA+Rwhao1h8F4XPxLnAF3+mUEQN+gbpVK5ZRXOj957aym2sC92r4Yxgin0EFHfUe1kAF7THTV2BKwxDs1FwfZoZ5xVEq7Y2UWP45tDo0kAbASYfpiCX+J5Mhn+MPRglP4q1lUGyC7rBwNshIkrATVpeOkary1muTM91y91KNmGOrhPWuvq0MLrKLiVZEKzK/aVLlytmhctV73jgIJaTHNg2Ecc2rRmR7BILaNYJXcXOznMTlx5pg1eoaE+QJT/Bx3uF59pOvhS2HojQVdWJEw5q1eY9ckjlxaaddt/L2lDeAyn4G7iO/jq+mWfUvR5gtH2IKsdiHYIFP2b150xb9G/mA6I9u5lWWtL3YWbPc0ujVWb7UKNpDpmmNlzbimo41gueCW4Icsvs889pNrecVxaA9M2k3EeaaKTt2yAAoBbJwSBqmqXgFGAlknDNmc8lMfSYAWHnT33KwXtgvmOnqH/TKA+zlstNfnkYxA13FAvw==,iv:3poj91BRr4NjFKNv5/+pBk1r8dQ3xsJ+Sv9fMBNog4A=,tag:lWdurnsnu/56wgSzgtO6Hw==,type:str]
    - ENC[AES256_GCM,data:O5+mVBsW1spnZ+Ad2pVyRj/34m3YpfllCAsfItvkd5Zw0HOCXEza/qjpuQGTMatt/46/oMtIhEvS6ldfW8SxX67ExJrsL/rcEdcAYlHM8I/NR6XnAUItGX3oR0A5Zqo+NnuzuA5Hv55R1DIzaY0p78nSwLZOPRawnQb1kp0fTvN8x4kDEKDpauSpkcr52g+hij5GlSCwF83zuj2ZQgz7KqzQLGcUkGHwmHjAS+ZqfB+T+xklsGKm4TfHKNXQrBzby+OQLew+G4rsVLAL5l6kCSOMxUiLe44H6IBFYUGSG4mhiN7OYrP28FOnvCGvI60Do7v6kmUeyGrkDW0ZErwaTmDTpnOHpKcLcWLlqav9cstbpYJc057P7xiqY/w7j2RlJYyWPSGCCw3mYcqIFBuedizOwzvnFJW9oDia8U1jq/wSMXxd6VoKy70bsPBzU2MIKCWI4gCgLHQjKjHB2gMhdXyJ2o6TEmUrIfDIFlP54uzZ3hhTtC4JIeZP5hPlJFwzGvwFvNpxITkYY6OgNC4yMP6aScr92w==,iv:Jv+BR5DxrwKfj9MfYD0NSXjR9BqE+jynW+ePw9xcjq8=,tag:WhEwjo8gBnDQyAYmIamN9g==,type:str]
    - ENC[AES256_GCM,data:CR/4+cpgpIG1ZmDyGCKCAdMVaJBpO625dsMhTgH1aeOlKd538Ps5yjhx2mSHIg77N6VUZhGpJ9WbU24FSulsjrJys9xR3EOa26xWCCcl92a3KU1DFiXc6YbqLIiVcelbdD3O9zQP0vQD9Pum9hpivGiXAEWBeuw=,iv:3O6AwuB8UNC4VUvxrr+NDKwCBb1FXAoJWUWIfL8PnR8=,tag:TZ16p+d4Ya8es15CTySpjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgqz87qgxh8qg8urrccz3tlr3htugwpk4sucmfys2k3c9srwv9aquzlguj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeDBDSjI1dFBrcjNsTzFN
            eGRjWU82ZlJ1WjNObWJlZWtwME9YZnRpUENJCm5mbnVUU0tXdGFueFNZL0I0Ylor
            TC9pSGJrMW94YWFKeGVQcnBocVpCMG8KLS0tIFNHYnIzdUo3OVRNK2NGQ2xXVWZ4
            bkxqdXlkZEFFdFk3Uncvb084OEhHSHMK/0zGyFKtKbQZXr6JbX5xiWbI8MGF3brA
            WPxUjHzOTtkDLGarSAcekZH5S0aauNyeJQofJJC6jUCHkZCbk8EuNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T18:54:52Z"
    mac: ENC[AES256_GCM,data:vtaivnY01VYr1+05jgqHHhjG1oAGrapZhhlP45TMNJY6KcxMz4BtrTzJQhspyXdWbWHjP8qqeoebHyG7VrZYZmwR/CbGTkavXP4ZH6ti+FKYjd52AMagGLkLC4dQDqh+y11EwIQHzCrv/WgQUO60rwFcH9RoQWO8fz02JC3c7jI=,iv:zLAj0OUBcpAj5+U1QVm17FPDv+j7qMqqPbue7eCyg4o=,tag:r2xUK+SwIYSv8Cg2n7G5ng==,type:str]
    pgp:
        - created_at: "2024-06-24T09:58:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Df7voni2Kxl4SAQdAY/7ld6p/G6dcT+aD49unYnAiPqAPOaEyBw1juKzw7RQw
            wSudrhsM9qVhO4kUvtwe81A/+tvCGsrQdmSKxGUXMcKKYFGnz5XLcHerGDGp2PO/
            0l4BVq6gusGrzYY8mVyspjV22Iu4Jx2P4a8PJe0g6iW7db8agvPH5r4+8Uf+IfR6
            2zuybS9o0rR+6RFINZZzN8N7b0JbVJmVuZYlQr1nWsHaBazM2DQj6vMAsdlTOeDF
            =M/SN
            -----END PGP MESSAGE-----
          fp: CE12ED73C6D5DE0516516DCC397761D5D102CB9D
        - created_at: "2024-06-24T09:58:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA7b93FlXgFUkAQgAxRfnE8dJOiCafpjDVzQB0V+YfpJ8NjXlaBZi9HiIIdSi
            WQHBDq5QMBDp9WLjBj2A8Aq2fdRQZGY2C/DFTLfEFLlGDe1KkCWqRr/4GUPtnOoG
            HZevB5SI3CxPhucCGn/g3wsayMtq1RsRMS9gWjieHYHziLJ/zSmpLdmBosPIBKGm
            PswH5KycwHoKGuSYuduF1yjVx5TKVQYg9GFA4i3wc5h5cb8Qbzsp0owB/ydSAvel
            9j6gd7IA4Uc3QC2go29P6K1/lql0dLznIHw2Ba4dwX+UOAIZci80ggwzroauJBlt
            dpqQ+5+QuYnTBhOa623sTRcR7fN31KRGl+lPkTMIn9JeAV5UV37RsCQaxw1Se7az
            QFeVkTR5YOipkWuF6xil36tU1SDn1awtvVXVN3VRYZp1hax9z0nM0r2jiThYC7WG
            hZKqrTyNNz8ryt0L+utkdjThLfN4TqeuqCz8VIuLww==
            =NtGV
            -----END PGP MESSAGE-----
          fp: 3C2F2605E078A1E18F4793909C4DBE6CF438F333
        - created_at: "2024-06-24T09:58:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtNl1HXvePigSAQdAXN3G2/TboXCwJ3GTcmnhE35mcvppfpgLyRKBSK0C9wkw
            OTUYQI1HfqT6SFAPeI97Y50wk/oijYAWGL+1xLkdiDNmQEu0QSuo0WJT2tawzJLF
            1GgBCQIQT5eTNNGpeqijKQrWY5wi16ap5hefqnDwhSMUVXW4+8GPEPleUiKaxpKy
            93By/pp3DTlDe0dg3nIxJenZLT/RKGliKzaAi1mfjBICP5zXP7lC7IKM+nLSk5g/
            1sznkkwaHG5Rww==
            =U6/+
            -----END PGP MESSAGE-----
          fp: DD939AD813A3EACB116A7F4B28244753C35D3D10
    unencrypted_suffix: _unencrypted
    version: 3.8.1
