secretKey: ENC[AES256_GCM,data:HZuBJIZTMdcHheGCuhqO6Q==,iv:ErHvC+nh/AFTzMohM1Vpyb4schZtmT7fP6GgsDSnii0=,tag:Ui00RhuVGqbcRQcpeikYtw==,type:str]
harborAdminPassword: ENC[AES256_GCM,data:4vGqGiSyOY4njpO+PQ==,iv:YHrL2hA0ypQbymd//gR9MWRFDqU9d32dso/Yk1RjMnY=,tag:ppm/NXTveGz2rPCDgFJllw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgqz87qgxh8qg8urrccz3tlr3htugwpk4sucmfys2k3c9srwv9aquzlguj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZXcxUkkrM1VaNG9GallX
            T3p5SU5YR0FSbG04aWVzeUxnZGFyS2k3NFM0CmQ2MEhMcmozdDJFK1l4V242MEpq
            ekRRUWtSdHQwdG1VdklqVUFNODJpR2MKLS0tIHVLdGdYSm5PZjRjQXd4a2c2YzhX
            eTFCaVMxdFZ4SnpzODFIT2g5WTB0MGcKLeXyoiO4CnBuynyYWnzj3SE+Az2uniQx
            cSemuYt/ohqgiyI+3zDogMhJq0TDVJeFzful+AGwabNixUC8gHqEnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T17:27:58Z"
    mac: ENC[AES256_GCM,data:wWX5iPBsi139eqN1329EgXivAHxMzRzjNeiqstISMmPt9mgMDCNU4pJIXPe+AvSFWEl49xQt+xQCb2AtyOJGcSeYJxoeucKqvQNqsPdOFi8ZZoEf44tJSfiWl7oEtX7joXoHhkEEeyAi7ihSxHE3h7A6+nggt0CKcOuE/3RvDMg=,iv:9lkM5F19IgaNj+4mWp5L377nqOA5xmn5pzCY3DqoN3A=,tag:J7gMvVLIJIKhYgotJvWs3w==,type:str]
    pgp:
        - created_at: "2024-06-24T09:58:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Df7voni2Kxl4SAQdAdzbaj/dBobg3JE9qNr9KvhKNYXEA6cZBkREd4OAMkjQw
            fHE8dQWaYIwWd02H4jQ6RG5t4D+h6MRpwGJ9m/BHIH8mg71CB0uH4DmvmQU/n4tc
            0l4B427ML2rbdd66j7+6GXlIgSrXODtsc0/PLxl2o5TP9EmT/oEezl7N+UPK8eBi
            l0iqIqLzE1lS4hK1Tse8AA0oMlEygHP85e8CsX1p+rPCki6Ye4oqeevk+r6FCrtu
            =HG4y
            -----END PGP MESSAGE-----
          fp: CE12ED73C6D5DE0516516DCC397761D5D102CB9D
        - created_at: "2024-06-24T09:58:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA7b93FlXgFUkAQf9HkYCCr97GAB7q/DDfwCt8CH4f1QF+whRT60XLOgPTHtQ
            PQaTzM+Xrfpqv6hIPrbWz+8qUAxF2s1egfvLxQDv70DUbFhyhhEiR3apl3RhV8Bo
            x7cDrbGQoRrbEPDSsrZ70MX++/D97GKJeo2E0EU4sx2ZZtBFw7vOlFb29WtUUaDg
            aHVVOa5hUfz6IpcC0neh0isMLO5xwDESQc15a7Wr2cDkuYlUDbAtCDNSdt7LrRtn
            EMgfGS1fcV/6Tjgndab9diK2WaxQjUkqfMDsdcSlOw8hkiczPSq9sV7NMHZfcvLl
            Esk376ebHVLgzmijPWG7PSK8LezWlABt244mWsIoptJeAWsXH81IfYSGlPVcyQnK
            M3Br0ZpUpic0p2ygu1UoZA8TLhu0DD6L2KDRsFq9iC6Q97vHoC43wI2tw0zH4OL3
            LFmLpeIFdY1KnSBSODskhAIQlisJXhmQ7JVg9lGS6w==
            =Rzj7
            -----END PGP MESSAGE-----
          fp: 3C2F2605E078A1E18F4793909C4DBE6CF438F333
        - created_at: "2024-06-24T09:58:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtNl1HXvePigSAQdAk7z/sxXSmvqTV2ivMbbeB9mAiD0CY0r5dE01WRlM8H4w
            vEv2qli2ZhbcezW6MoBpDTb7bC4PCA6jSp/1jcoaA48Om9YB2qg4+4zNSTE/6bG8
            1GgBCQIQ5Bx4015ao0iG6tAvws/Uv5Apf+KS3EcDNQfcriLgS5vpgOouGUc3YxhA
            SOo/TGwe+ieb38mS0BrqGBDxuC1xqFpWvq9gtb7cPSPmcdgGDEfIdiXHi/aqbkPN
            E7ThRoMx75HUhw==
            =2Fkw
            -----END PGP MESSAGE-----
          fp: DD939AD813A3EACB116A7F4B28244753C35D3D10
    unencrypted_suffix: _unencrypted
    version: 3.8.1
