apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
spec:
  project: default
  destination:
    namespace: argocd
    name: in-cluster
  sources:
    - repoURL: "https://argoproj.github.io/argo-helm"
      chart: argo-cd
      targetRevision: 7.2.0
      helm:
        valueFiles:
          - $values/kubernetes/applications/argocd/values.yaml
          - secrets://https://raw.githubusercontent.com/nfits/dhm-infra/main/kubernetes/applications/argocd/values.sops.yaml
        ignoreMissingValueFiles: false
    - repoURL: https://github.com/nfits/dhm-infra.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        gateway-access/main: "true"
    syncOptions:
      - CreateNamespace=true
