apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
spec:
  project: default
  destination:
    namespace: cert-manager
    name: in-cluster
  sources:
    - repoURL: "https://charts.jetstack.io"
      chart: cert-manager
      targetRevision: 1.15.0
      helm:
        valueFiles:
          - $values/kubernetes/applications/cert-manager/values.yaml
          - secrets://https://raw.githubusercontent.com/nfits/dhm-infra/main/kubernetes/applications/cert-manager/values.sops.yaml
    - repoURL: https://github.com/nfits/dhm-infra.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
