apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: d2vm-dockerd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
spec:
  project: default
  destination:
    namespace: d2vm-dockerd
    name: in-cluster
  source:
    path: kubernetes/applications/d2vm-dockerd
    repoURL: https://github.com/nfits/dhm-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
