apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
spec:
  project: default
  destination:
    namespace: external-dns
    name: in-cluster
  sources:
    - repoURL: "https://charts.bitnami.com/bitnami"
      chart: external-dns
      targetRevision: 8.0.0
      helm:
        valueFiles:
          - $values/kubernetes/applications/external-dns/values.yaml
          - secrets://https://raw.githubusercontent.com/nfits/dhm-infra/main/kubernetes/applications/external-dns/values.sops.yaml
    - repoURL: https://github.com/nfits/dhm-infra.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
