apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
spec:
  project: default
  destination:
    namespace: harbor
    name: in-cluster
  sources:
    - repoURL: "https://helm.goharbor.io"
      chart: harbor
      targetRevision: 1.15.0
      helm:
        valueFiles:
          - $values/kubernetes/applications/harbor/values.yaml
          - secrets://https://raw.githubusercontent.com/nfits/dhm-infra/main/kubernetes/applications/harbor/values.sops.yaml
        ignoreMissingValueFiles: false
    - repoURL: https://github.com/nfits/dhm-infra.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/nfits/dhm-infra.git
      targetRevision: main
      path: kubernetes/applications/harbor/extra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        gateway-access/main: "true"
    syncOptions:
      - CreateNamespace=true
