apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
spec:
  project: default
  destination:
    namespace: gateway-system
    name: in-cluster
  sources:
    - repoURL: https://github.com/nginxinc/nginx-gateway-fabric.git
      targetRevision: v1.3.0
      path: config/crd/gateway-api/standard
    - repoURL: https://github.com/nginxinc/nginx-gateway-fabric.git
      targetRevision: v1.3.0
      path: config/crd/gateway-api/experimental
    - repoURL: ghcr.io/nginxinc/charts
      chart: nginx-gateway-fabric
      targetRevision: 1.3.0
      helm:
        valueFiles:
          - $values/kubernetes/applications/nginx-gateway-fabric/values.yaml
    - repoURL: https://github.com/nfits/dhm-infra.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/nfits/dhm-infra.git
      targetRevision: main
      path: kubernetes/applications/nginx-gateway-fabric/extra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
