networkPolicies:
  enabled: true
  type: "k3s"

persistence:
  defaultDataLocality: best-effort

defaultSettings:
  # Only create on nodes with label node.longhorn.io/create-default-disk=true
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn/
  replicaAutoBalance: best-effort
  defaultDataLocality: best-effort
  allowCollectingLonghornUsageMetrics: false
  storageReservedPercentageForDefaultDisk: 10
  concurrentAutomaticEngineUpgradePerNodeLimit: 1

# Override the images with ones built using the Dockerfile in misc/longhorn
# This fixes path issues on NixOS
image:
  longhorn:
    manager:
      repository: patricknfits/longhorn-manager
    instanceManager:
      repositoty: patricknfits/longhorn-instance-manager
