k8sServiceHost: "api.cluster.dhm-ctf.de"
k8sServicePort: "6443"

rollOutCiliumPods: true

operator:
  rollOutPods: true

envoy:
  enabled: true
  rollOutPods: true

forceDeviceDetection: true

kubeProxyReplacement: "true"
bpf:
  masquerade: true
  hostLegacyRouting: false

routingMode: "native"
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: "10.250.0.0/16"

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true

loadBalancer:
  mode: dsr
  algorithm: maglev

ipam:
  mode: kubernetes

l2announcements:
  enabled: true

l2podAnnouncements:
  enabled: true
  interface: cluster

hubble:
  enabled: true

  relay:
    enabled: true
    rollOutPods: true

  ui:
    enabled: true
    rollOutPods: true

# FIXME: Remove
debug:
  enabled: true
  verbose: envoy
