apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-builder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-builder
  namespace: ctf-platform
rules:
  # Required for rollout restart
  - apiGroups: [ "apps" ]
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs: [ "get", "patch" ]
  # Required to load platform config
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "list", "get" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-builder
  namespace: ctf-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-builder
subjects:
  - kind: ServiceAccount
    name: platform-builder
    namespace: arc-system
