apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: api
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: grpc
      appProtocol: kubernetes.io/h2c
