{{ if .Values.frontend.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- with .Values.frontend.httpRoute.parentRefs }}
    {{- toYaml . | trim | nindent 6 }}
    {{- end }}
  hostnames:
    {{- with .Values.frontend.httpRoute.hostnames }}
    {{- toYaml . | trim | nindent 6 }}
    {{- end }}
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}-frontend
          port: 80
{{ end }}
