{{ if .Values.staticFiles.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-static-files
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- with .Values.staticFiles.httpRoute.parentRefs }}
    {{- toYaml . | trim | nindent 6 }}
    {{- end }}
  hostnames:
    {{- with .Values.staticFiles.httpRoute.hostnames }}
    {{- toYaml . | trim | nindent 6 }}
    {{- end }}
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}-static-files
          port: 80
{{ end }}
