apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-static-files
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: static-files
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: http
