apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor
spec:
  parentRefs:
    - name: main
      namespace: gateway-system
      sectionName: https
  hostnames:
    - harbor.dhm-ctf.de
  rules:
    - backendRefs:
        - name: harbor
          port: 80
